
version: 2

models:
  - name: dim_airport
    description: "dim airport model"
    columns:
      - name: airport_code
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_aircraft
    description: "dim air craft model"
    columns:
      - name: aircraft_code
        description: "The primary key for this table"
        tests:
          - unique
          - not_null